"""
Plot equity curve generated by the IBPrice backtest.

Usage:
    python plot_equity_curve.py
    python plot_equity_curve.py --input backtest_output/equity_curve.csv --output backtest_output/equity_curve.png
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot equity curve from backtest output CSV.")
    parser.add_argument(
        "--input",
        default="backtest_output/equity_curve.csv",
        help="Path to equity_curve.csv",
    )
    parser.add_argument(
        "--output",
        default="backtest_output/equity_curve.png",
        help="Path for output image",
    )
    return parser.parse_args()


def load_equity_points(csv_path: Path) -> tuple[list[datetime], list[float]]:
    times: list[datetime] = []
    equity_values: list[float] = []
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            ts = datetime.strptime(row["timestamp"], "%Y-%m-%d %H:%M:%S")
            eq = float(row["equity"])
            times.append(ts)
            equity_values.append(eq)
    return times, equity_values


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        raise SystemExit(f"Input file not found: {input_path}")

    times, equity_values = load_equity_points(input_path)
    if not times:
        raise SystemExit("No equity points found in input CSV.")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(12, 5))
    plt.plot(times, equity_values, linewidth=1.8, label="Equity")
    plt.title("Backtest Equity Curve")
    plt.xlabel("Time")
    plt.ylabel("Equity (HKD)")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()

    print(f"Saved equity curve plot to: {output_path.resolve()}")


if __name__ == "__main__":
    main()

